# Generated by Django 3.0.2 on 2020-01-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jayanta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=125, null=True),
        ),
    ]
